name = "lustre_omnistate"
version = "0.0.3"

description = "Use Remote State, Locally"
repository = { type = "github", user = "weedonandscott", repo = "lustre_omnistate" }
licences = ["MIT"]

internal_modules = ["lustre_omnistate/internal", "lustre_omnistate/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
lustre = ">= 4.6.1 and < 5.0.0"
lustre_websocket = ">= 0.7.6 and < 1.0.0"
mist = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 0.30.0 and < 1.0.0"
gleam_otp = ">= 0.14.1 and < 1.0.0"
gleam_fetch = ">= 1.0.1 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
wisp = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
