name = "omnimessage_server"
version = "0.2.0"

description = "Use Remote State, Locally"
repository = { type = "github", user = "weedonandscott", repo = "omnimessage" }
licences = ["MIT"]

internal_modules = ["omnimessage/server/internal", "omnimessage/server/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 0.14.1 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
mist = ">= 4.0.0 and < 5.0.0"
wisp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 0.30.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
