name = "omnimessage_lustre"
version = "0.3.0"
target = "javascript"

description = "Use Remote State, Locally"
repository = { type = "github", user = "weedonandscott", repo = "omnimessage" }
licences = ["MIT"]

internal_modules = ["omnimessage/lustre/internal", "omnimessage/lustre/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
gleam_fetch = ">= 1.0.1 and < 2.0.0"
gleam_http = ">= 3.0.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
