name = "server"
version = "0.1.0"
gleam = ">= 1.5.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.0 and < 5.0.0"
wisp = ">= 1.2.0 and < 2.0.0"
mist = ">= 4.0.0 and < 5.0.0"
gleam_erlang = ">= 0.28.0 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
lustre_pipes = ">= 0.0.1 and < 1.0.0"
omnimessage_server = { path = "../../omnimessage_server" }
shared = { path = "../shared" }
gleam_otp = ">= 0.13.0 and < 1.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
decode = ">= 1.1.0 and < 2.0.0"
carpenter = ">= 0.3.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
